# Generated by Django 3.2.13 on 2022-05-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_review_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='excerpt',
            new_name='author',
        ),
    ]
