# Generated by Django 3.2.13 on 2022-05-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.IntegerField(choices=[(0, '--------'), (1, 'Crime'), {'Romance', 2}], default=0),
        ),
    ]
