# Generated by Django 3.2.13 on 2022-05-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_review_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.IntegerField(blank=True, choices=[(0, 'Crime'), (1, 'Fantasy'), (2, 'Horror'), (4, 'Kids'), (5, 'Mystery'), (6, 'Romance'), (7, 'Science-Fiction'), (8, 'Teen'), (9, 'Thriller'), (10, 'Other')], null=True),
        ),
    ]
