# Generated by Django 3.2.13 on 2022-05-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220530_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blog.genre'),
        ),
    ]
