# Generated by Django 3.2.13 on 2022-05-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
